/// Short medical disclaimer shown throughout the app
const kMedicalDisclaimer =
    '⚠️  Disclaimer: The information shown in LibreTrac is for educational '
    'purposes only, may contain errors, and is **NOT** medical advice.  '
    'Always talk to a qualified clinician before making changes.';

/// AI-specific disclaimer for drug information
const kAIDisclaimer =
    '🤖 AI-Generated Content: This information was generated by AI and may '
    'contain inaccuracies or errors. AI can hallucinate facts and should '
    'never be relied upon for medical decisions. Always verify with a '
    'qualified healthcare professional.';

/// First launch disclaimer title
const kFirstLaunchDisclaimerTitle = 'Important Notice';

/// First launch disclaimer content shown on first app open
const kFirstLaunchDisclaimer = '''
Welcome to LibreTrac!

Before you begin, please read and understand the following:

⚠️ **Not Medical Advice**
This app is for personal tracking and educational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment.

🤖 **AI Limitations**
LibreTrac uses AI to provide drug information and analyze trends. AI can make mistakes, hallucinate facts, and provide inaccurate information. Never make medical decisions based solely on AI-generated content.

💊 **Medications & Supplements**
• Always consult a doctor or pharmacist before starting, stopping, or changing any medication
• The app does not check for drug interactions — you are responsible for verifying safety with a healthcare provider
• Track your medications accurately and bring this information to your appointments

📊 **Data Tracking**
Your mood, sleep, and cognitive data are stored locally on your device. This data is meant to help you identify patterns and have informed conversations with healthcare providers.

By continuing, you acknowledge that you understand these limitations and agree to use this app responsibly.
''';
